<iframe src="https://www.paytr.com/odeme/api/<?php echo json_decode($this->getAction())->token;?>" id="paytriframe" frameborder="0" scrolling="no" style="width: 100%;"></iframe>
<script type="text/javascript">
    require([
        "Paytr_Transfer/js/iframeResizerBankTransfer.min",
        "domReady"
    ], function (iFrameResize) {
        iFrameResize({},'#paytriframetransfer');
    });
</script>
