<?php
$action = json_decode($block->getAction());
$token = isset($action->token) ? $action->token : '';
?>

<iframe src="https://www.paytr.com/odeme/api/<?= $block->escapeUrl($token) ?>"
        id="paytriframe"
        frameborder="0"
        scrolling="no"
        style="width: 100%;">
</iframe>
<script type="text/javascript">
    require([
        "Paytr_Transfer/js/iframeResizerBankTransfer.min",
        "domReady"
    ], function (iFrameResize) {
        iFrameResize({},'#paytriframetransfer');
    });
</script>
